#ifndef __BMBoards_h__
#define __BMBoards_h__
  #if defined (__AVR_AT94K__)
    #define __BM_BOARD__ "AT94K"
  #elif defined (__AVR_AT43USB320__)
    #define __BM_BOARD__ "AT43USB320"
  #elif defined (__AVR_AT43USB355__)
    #define __BM_BOARD__ "AT43USB355"
  #elif defined (__AVR_AT76C711__)
    #define __BM_BOARD__ "AT76C711"
  #elif defined (__AVR_AT86RF401__)
    #define __BM_BOARD__ "AT86RF401"
  #elif defined (__AVR_AT90PWM1__)
    #define __BM_BOARD__ "AT90PWM1"
  #elif defined (__AVR_AT90PWM2__)
    #define __BM_BOARD__ "AT90PWM2"
  #elif defined (__AVR_AT90PWM2B__)
    #define __BM_BOARD__ "AT90PWM2B"
  #elif defined (__AVR_AT90PWM3__)
    #define __BM_BOARD__ "AT90PWM3"
  #elif defined (__AVR_AT90PWM3B__)
    #define __BM_BOARD__ "AT90PWM3B"
  #elif defined (__AVR_AT90PWM216__)
    #define __BM_BOARD__ "AT90PWM216"
  #elif defined (__AVR_AT90PWM316__)
    #define __BM_BOARD__ "AT90PWM316"
  #elif defined (__AVR_AT90PWM161__)
    #define __BM_BOARD__ "AT90PWM161"
  #elif defined (__AVR_AT90PWM81__)
    #define __BM_BOARD__ "AT90PWM81"
  #elif defined (__AVR_ATmega8U2__)
    #define __BM_BOARD__ "ATmega8U2"
  #elif defined (__AVR_ATmega16M1__)
    #define __BM_BOARD__ "ATmega16M1"
  #elif defined (__AVR_ATmega16U2__)
    #define __BM_BOARD__ "ATmega16U2"
  #elif defined (__AVR_ATmega16U4__)
    #define __BM_BOARD__ "ATmega16U4"
  #elif defined (__AVR_ATmega32C1__)
    #define __BM_BOARD__ "ATmega32C1"
  #elif defined (__AVR_ATmega32M1__)
    #define __BM_BOARD__ "ATmega32M1"
  #elif defined (__AVR_ATmega32U2__)
    #define __BM_BOARD__ "ATmega32U2"
  #elif defined (__AVR_ATmega32U4__)
    #define __BM_BOARD__ "ATmega32U4"
  #elif defined (__AVR_ATmega32U6__)
    #define __BM_BOARD__ "ATmega32U6"
  #elif defined (__AVR_ATmega64C1__)
    #define __BM_BOARD__ "ATmega64C1"
  #elif defined (__AVR_ATmega64M1__)
    #define __BM_BOARD__ "ATmega64M1"
  #elif defined (__AVR_ATmega128__)
    #define __BM_BOARD__ "ATmega128"
  #elif defined (__AVR_ATmega128A__)
    #define __BM_BOARD__ "ATmega128A"
  #elif defined (__AVR_ATmega1280__)
    #define __BM_BOARD__ "ATmega1280"
  #elif defined (__AVR_ATmega1281__)
    #define __BM_BOARD__ "ATmega1281"
  #elif defined (__AVR_ATmega1284__)
    #define __BM_BOARD__ "ATmega1284"
  #elif defined (__AVR_ATmega1284P__)
    #define __BM_BOARD__ "ATmega1284P"
  #elif defined (__AVR_ATmega128RFA1__)
    #define __BM_BOARD__ "ATmega128RFA1"
  #elif defined (__AVR_ATmega1284RFR2__)
    #define __BM_BOARD__ "ATmega1284RFR2"
  #elif defined (__AVR_ATmega128RFR2__)
    #define __BM_BOARD__ "ATmega128RFR2"
  #elif defined (__AVR_ATmega2564RFR2__)
    #define __BM_BOARD__ "ATmega2564RFR2"
  #elif defined (__AVR_ATmega256RFR2__)
    #define __BM_BOARD__ "ATmega256RFR2"
  #elif defined (__AVR_ATmega2560__)
    #define __BM_BOARD__ "ATmega2560"
  #elif defined (__AVR_ATmega2561__)
    #define __BM_BOARD__ "ATmega2561"
  #elif defined (__AVR_AT90CAN32__)
    #define __BM_BOARD__ "AT90CAN32"
  #elif defined (__AVR_AT90CAN64__)
    #define __BM_BOARD__ "AT90CAN64"
  #elif defined (__AVR_AT90CAN128__)
    #define __BM_BOARD__ "AT90CAN128"
  #elif defined (__AVR_AT90USB82__)
    #define __BM_BOARD__ "AT90USB82"
  #elif defined (__AVR_AT90USB162__)
    #define __BM_BOARD__ "AT90USB162"
  #elif defined (__AVR_AT90USB646__)
    #define __BM_BOARD__ "AT90USB646"
  #elif defined (__AVR_AT90USB647__)
    #define __BM_BOARD__ "AT90USB647"
  #elif defined (__AVR_AT90USB1286__)
    #define __BM_BOARD__ "AT90USB1286"
  #elif defined (__AVR_AT90USB1287__)
    #define __BM_BOARD__ "AT90USB1287"
  #elif defined (__AVR_ATmega644RFR2__)
    #define __BM_BOARD__ "ATmega644RFR2"
  #elif defined (__AVR_ATmega64RFR2__)
    #define __BM_BOARD__ "ATmega64RFR2"
  #elif defined (__AVR_ATmega64__)
    #define __BM_BOARD__ "ATmega64"
  #elif defined (__AVR_ATmega64A__)
    #define __BM_BOARD__ "ATmega64A"
  #elif defined (__AVR_ATmega640__)
    #define __BM_BOARD__ "ATmega640"
  #elif defined (__AVR_ATmega644__)
    #define __BM_BOARD__ "ATmega644"
  #elif defined (__AVR_ATmega644A__)
    #define __BM_BOARD__ "ATmega644A"
  #elif defined (__AVR_ATmega644P__)
    #define __BM_BOARD__ "ATmega644P"
  #elif defined (__AVR_ATmega644PA__)
    #define __BM_BOARD__ "ATmega644PA"
  #elif defined (__AVR_ATmega645__)
    #define __BM_BOARD__ "ATmega645"
  #elif defined (__AVR_ATmega645A__)
    #define __BM_BOARD__ "ATmega645A"
  #elif defined (__AVR_ATmega645P__)
    #define __BM_BOARD__ "ATmega645P"
  #elif defined (__AVR_ATmega6450__)
    #define __BM_BOARD__ "ATmega6450"
  #elif defined (__AVR_ATmega6450A__)
    #define __BM_BOARD__ "ATmega6450A"
  #elif defined (__AVR_ATmega6450P__)
    #define __BM_BOARD__ "ATmega6450P"
  #elif defined (__AVR_ATmega649__)
    #define __BM_BOARD__ "ATmega649"
  #elif defined (__AVR_ATmega649A__)
    #define __BM_BOARD__ "ATmega649A"
  #elif defined (__AVR_ATmega6490__)
    #define __BM_BOARD__ "ATmega6490"
  #elif defined (__AVR_ATmega6490A__)
    #define __BM_BOARD__ "ATmega6490A"
  #elif defined (__AVR_ATmega6490P__)
    #define __BM_BOARD__ "ATmega6490P"
  #elif defined (__AVR_ATmega649P__)
    #define __BM_BOARD__ "ATmega649P"
  #elif defined (__AVR_ATmega64HVE__)
    #define __BM_BOARD__ "ATmega64HVE"
  #elif defined (__AVR_ATmega64HVE2__)
    #define __BM_BOARD__ "ATmega64HVE2"
  #elif defined (__AVR_ATmega103__)
    #define __BM_BOARD__ "ATmega103"
  #elif defined (__AVR_ATmega32__)
    #define __BM_BOARD__ "ATmega32"
  #elif defined (__AVR_ATmega32A__)
    #define __BM_BOARD__ "ATmega32A"
  #elif defined (__AVR_ATmega323__)
    #define __BM_BOARD__ "ATmega323"
  #elif defined (__AVR_ATmega324P__)
    #define __BM_BOARD__ "ATmega324P"
  #elif defined (__AVR_ATmega324A__)
    #define __BM_BOARD__ "ATmega324A"
  #elif defined (__AVR_ATmega324PA__)
    #define __BM_BOARD__ "ATmega324PA"
  #elif defined (__AVR_ATmega325__)
    #define __BM_BOARD__ "ATmega325"
  #elif defined (__AVR_ATmega325A__)
    #define __BM_BOARD__ "ATmega325A"
  #elif defined (__AVR_ATmega325P__)
    #define __BM_BOARD__ "ATmega325P"
  #elif defined (__AVR_ATmega325PA__)
    #define __BM_BOARD__ "ATmega325PA"
  #elif defined (__AVR_ATmega3250__) 
  #elif defined (__AVR_ATmega3250A__)
    #define __BM_BOARD__ "ATmega3250A"
  #elif defined (__AVR_ATmega3250P__)
    #define __BM_BOARD__ "ATmega3250P"
  #elif defined (__AVR_ATmega3250PA__)
    #define __BM_BOARD__ "ATmega3250PA"
  #elif defined (__AVR_ATmega328P__)
    // 28 pins minus power for raw chip
    #define BM_MAX_PINS 23
    #define __BM_BOARD__ "ATmega328P"
  #elif defined (__AVR_ATmega328__)
    #define __BM_BOARD__ "ATmega328"
  #elif defined (__AVR_ATmega329__)
    #define __BM_BOARD__ "ATmega329"
  #elif defined (__AVR_ATmega329A__)
    #define __BM_BOARD__ "ATmega329A"
  #elif defined (__AVR_ATmega329P__) 
  #elif defined (__AVR_ATmega329PA__)
    #define __BM_BOARD__ "ATmega329PA"
  #elif defined (__AVR_ATmega3290PA__)
    #define __BM_BOARD__ "ATmega3290PA"
  #elif defined (__AVR_ATmega3290__)
    #define __BM_BOARD__ "ATmega3290"
  #elif defined (__AVR_ATmega3290A__)
    #define __BM_BOARD__ "ATmega3290A"
  #elif defined (__AVR_ATmega3290P__)
    #define __BM_BOARD__ "ATmega3290P"
  #elif defined (__AVR_ATmega32HVB__)
    #define __BM_BOARD__ "ATmega32HVB"
  #elif defined (__AVR_ATmega32HVBREVB__)
    #define __BM_BOARD__ "ATmega32HVBREVB"
  #elif defined (__AVR_ATmega406__)
    #define __BM_BOARD__ "ATmega406"
  #elif defined (__AVR_ATmega16__)
    #define __BM_BOARD__ "ATmega16"
  #elif defined (__AVR_ATmega16A__)
    #define __BM_BOARD__ "ATmega16A"
  #elif defined (__AVR_ATmega161__)
    #define __BM_BOARD__ "ATmega161"
  #elif defined (__AVR_ATmega162__)
    #define __BM_BOARD__ "ATmega162"
  #elif defined (__AVR_ATmega163__)
    #define __BM_BOARD__ "ATmega163"
  #elif defined (__AVR_ATmega164P__)
    #define __BM_BOARD__ "ATmega164P"
  #elif defined (__AVR_ATmega164A__)
    #define __BM_BOARD__ "ATmega164A"
  #elif defined (__AVR_ATmega164PA__)
    #define __BM_BOARD__ "ATmega164PA"
  #elif defined (__AVR_ATmega165__)
    #define __BM_BOARD__ "ATmega165"
  #elif defined (__AVR_ATmega165A__)
    #define __BM_BOARD__ "ATmega165A"
  #elif defined (__AVR_ATmega165P__)
    #define __BM_BOARD__ "ATmega165P"
  #elif defined (__AVR_ATmega165PA__)
    #define __BM_BOARD__ "ATmega165PA"
  #elif defined (__AVR_ATmega168__)
    #define __BM_BOARD__ "ATmega168"
  #elif defined (__AVR_ATmega168A__)
    #define __BM_BOARD__ "ATmega168A"
  #elif defined (__AVR_ATmega168P__)
    #define __BM_BOARD__ "ATmega168P"
  #elif defined (__AVR_ATmega168PA__)
    #define __BM_BOARD__ "ATmega168PA"
  #elif defined (__AVR_ATmega168PB__)
    #define __BM_BOARD__ "ATmega168PB"
  #elif defined (__AVR_ATmega169__)
    #define __BM_BOARD__ "ATmega169"
  #elif defined (__AVR_ATmega169A__)
    #define __BM_BOARD__ "ATmega169A"
  #elif defined (__AVR_ATmega169P__)
    #define __BM_BOARD__ "ATmega169P"
  #elif defined (__AVR_ATmega169PA__)
    #define __BM_BOARD__ "ATmega169PA"
  #elif defined (__AVR_ATmega8HVA__)
    #define __BM_BOARD__ "ATmega8HVA"
  #elif defined (__AVR_ATmega16HVA__)
    #define __BM_BOARD__ "ATmega16HVA"
  #elif defined (__AVR_ATmega16HVA2__)
    #define __BM_BOARD__ "ATmega16HVA2"
  #elif defined (__AVR_ATmega16HVB__)
    #define __BM_BOARD__ "ATmega16HVB"
  #elif defined (__AVR_ATmega16HVBREVB__)
    #define __BM_BOARD__ "ATmega16HVBREVB"
  #elif defined (__AVR_ATmega8__)
    #define __BM_BOARD__ "ATmega8"
  #elif defined (__AVR_ATmega8A__)
    #define __BM_BOARD__ "ATmega8A"
  #elif defined (__AVR_ATmega48__)
    #define __BM_BOARD__ "ATmega48"
  #elif defined (__AVR_ATmega48A__)
    #define __BM_BOARD__ "ATmega48A"
  #elif defined (__AVR_ATmega48PA__)
    #define __BM_BOARD__ "ATmega48PA"
  #elif defined (__AVR_ATmega48PB__)
    #define __BM_BOARD__ "ATmega48PB"
  #elif defined (__AVR_ATmega48P__)
    #define __BM_BOARD__ "ATmega48P"
  #elif defined (__AVR_ATmega88__)
    #define __BM_BOARD__ "ATmega88"
  #elif defined (__AVR_ATmega88A__)
    #define __BM_BOARD__ "ATmega88A"
  #elif defined (__AVR_ATmega88P__)
    #define __BM_BOARD__ "ATmega88P"
  #elif defined (__AVR_ATmega88PA__)
    #define __BM_BOARD__ "ATmega88PA"
  #elif defined (__AVR_ATmega88PB__)
    #define __BM_BOARD__ "ATmega88PB"
  #elif defined (__AVR_ATmega8515__)
    #define __BM_BOARD__ "ATmega8515"
  #elif defined (__AVR_ATmega8535__)
    #define __BM_BOARD__ "ATmega8535"
  #elif defined (__AVR_AT90S8535__)
    #define __BM_BOARD__ "AT90S8535"
  #elif defined (__AVR_AT90C8534__)
    #define __BM_BOARD__ "AT90C8534"
  #elif defined (__AVR_AT90S8515__)
    #define __BM_BOARD__ "AT90S8515"
  #elif defined (__AVR_AT90S4434__)
    #define __BM_BOARD__ "AT90S4434"
  #elif defined (__AVR_AT90S4433__)
    #define __BM_BOARD__ "AT90S4433"
  #elif defined (__AVR_AT90S4414__)
    #define __BM_BOARD__ "AT90S4414"
  #elif defined (__AVR_ATtiny22__)
    #define __BM_BOARD__ "ATtiny22"
  #elif defined (__AVR_ATtiny26__)
    #define __BM_BOARD__ "ATtiny26"
  #elif defined (__AVR_AT90S2343__)
    #define __BM_BOARD__ "AT90S2343"
  #elif defined (__AVR_AT90S2333__)
    #define __BM_BOARD__ "AT90S2333"
  #elif defined (__AVR_AT90S2323__)
    #define __BM_BOARD__ "AT90S2323"
  #elif defined (__AVR_AT90S2313__)
    #define __BM_BOARD__ "AT90S2313"
  #elif defined (__AVR_ATtiny4__)
    #define __BM_BOARD__ "ATtiny4"
  #elif defined (__AVR_ATtiny5__)
    #define __BM_BOARD__ "ATtiny5"
  #elif defined (__AVR_ATtiny9__)
    #define __BM_BOARD__ "ATtiny9"
  #elif defined (__AVR_ATtiny10__)
    #define __BM_BOARD__ "ATtiny10"
  #elif defined (__AVR_ATtiny20__)
    #define __BM_BOARD__ "ATtiny20"
  #elif defined (__AVR_ATtiny40__)
    #define __BM_BOARD__ "ATtiny40"
  #elif defined (__AVR_ATtiny2313__)
    #define __BM_BOARD__ "ATtiny2313"
  #elif defined (__AVR_ATtiny2313A__)
    #define __BM_BOARD__ "ATtiny2313A"
  #elif defined (__AVR_ATtiny13__)
    #define __BM_BOARD__ "ATtiny13"
  #elif defined (__AVR_ATtiny13A__)
    #define __BM_BOARD__ "ATtiny13A"
  #elif defined (__AVR_ATtiny25__)
    #define __BM_BOARD__ "ATtiny25"
  #elif defined (__AVR_ATtiny4313__)
    #define __BM_BOARD__ "ATtiny4313"
  #elif defined (__AVR_ATtiny45__)
    #define __BM_BOARD__ "ATtiny45"
  #elif defined (__AVR_ATtiny85__)
    #define __BM_BOARD__ "ATtiny85"
  #elif defined (__AVR_ATtiny24__)
    #define __BM_BOARD__ "ATtiny24"
  #elif defined (__AVR_ATtiny24A__)
    #define __BM_BOARD__ "ATtiny24A"
  #elif defined (__AVR_ATtiny44__)
    #define __BM_BOARD__ "ATtiny44"
  #elif defined (__AVR_ATtiny44A__)
    #define __BM_BOARD__ "ATtiny44A"
  #elif defined (__AVR_ATtiny441__)
    #define __BM_BOARD__ "ATtiny441"
  #elif defined (__AVR_ATtiny84__)
    #define __BM_BOARD__ "ATtiny84"
  #elif defined (__AVR_ATtiny84A__)
    #define __BM_BOARD__ "ATtiny84A"
  #elif defined (__AVR_ATtiny841__)
    #define __BM_BOARD__ "ATtiny841"
  #elif defined (__AVR_ATtiny261__)
    #define __BM_BOARD__ "ATtiny261"
  #elif defined (__AVR_ATtiny261A__)
    #define __BM_BOARD__ "ATtiny261A"
  #elif defined (__AVR_ATtiny461__)
    #define __BM_BOARD__ "ATtiny461"
  #elif defined (__AVR_ATtiny461A__)
    #define __BM_BOARD__ "ATtiny461A"
  #elif defined (__AVR_ATtiny861__)
    #define __BM_BOARD__ "ATtiny861"
  #elif defined (__AVR_ATtiny861A__)
    #define __BM_BOARD__ "ATtiny861A"
  #elif defined (__AVR_ATtiny43U__)
    #define __BM_BOARD__ "ATtiny43U"
  #elif defined (__AVR_ATtiny48__)
    #define __BM_BOARD__ "ATtiny48"
  #elif defined (__AVR_ATtiny88__)
    #define __BM_BOARD__ "ATtiny88"
  #elif defined (__AVR_ATtiny828__)
    #define __BM_BOARD__ "ATtiny828"
  #elif defined (__AVR_ATtiny87__)
    #define __BM_BOARD__ "ATtiny87"
  #elif defined (__AVR_ATtiny167__)
    #define __BM_BOARD__ "ATtiny167"
  #elif defined (__AVR_ATtiny1634__)
    #define __BM_BOARD__ "ATtiny1634"
  #elif defined (__AVR_AT90SCR100__)
    #define __BM_BOARD__ "AT90SCR100"
  #elif defined (__AVR_ATxmega8E5__)
    #define __BM_BOARD__ "ATxmega8E5"
  #elif defined (__AVR_ATxmega16A4__)
    #define __BM_BOARD__ "ATxmega16A4"
  #elif defined (__AVR_ATxmega16A4U__)
    #define __BM_BOARD__ "ATxmega16A4U"
  #elif defined (__AVR_ATxmega16C4__)
    #define __BM_BOARD__ "ATxmega16C4"
  #elif defined (__AVR_ATxmega16D4__)
    #define __BM_BOARD__ "ATxmega16D4"
  #elif defined (__AVR_ATxmega16E5__)
    #define __BM_BOARD__ "ATxmega16E5"
  #elif defined (__AVR_ATxmega32A4__)
    #define __BM_BOARD__ "ATxmega32A4"
  #elif defined (__AVR_ATxmega32A4U__)
    #define __BM_BOARD__ "ATxmega32A4U"
  #elif defined (__AVR_ATxmega32C3__)
    #define __BM_BOARD__ "ATxmega32C3"
  #elif defined (__AVR_ATxmega32C4__)
    #define __BM_BOARD__ "ATxmega32C4"
  #elif defined (__AVR_ATxmega32D3__)
    #define __BM_BOARD__ "ATxmega32D3"
  #elif defined (__AVR_ATxmega32D4__)
    #define __BM_BOARD__ "ATxmega32D4"
  #elif defined (__AVR_ATxmega32E5__)
    #define __BM_BOARD__ "ATxmega32E5"
  #elif defined (__AVR_ATxmega64A1__)
    #define __BM_BOARD__ "ATxmega64A1"
  #elif defined (__AVR_ATxmega64A1U__)
    #define __BM_BOARD__ "ATxmega64A1U"
  #elif defined (__AVR_ATxmega64A3__)
    #define __BM_BOARD__ "ATxmega64A3"
  #elif defined (__AVR_ATxmega64A3U__)
    #define __BM_BOARD__ "ATxmega64A3U"
  #elif defined (__AVR_ATxmega64A4U__)
    #define __BM_BOARD__ "ATxmega64A4U"
  #elif defined (__AVR_ATxmega64B1__)
    #define __BM_BOARD__ "ATxmega64B1"
  #elif defined (__AVR_ATxmega64B3__)
    #define __BM_BOARD__ "ATxmega64B3"
  #elif defined (__AVR_ATxmega64C3__)
    #define __BM_BOARD__ "ATxmega64C3"
  #elif defined (__AVR_ATxmega64D3__)
    #define __BM_BOARD__ "ATxmega64D3"
  #elif defined (__AVR_ATxmega64D4__)
    #define __BM_BOARD__ "ATxmega64D4"
  #elif defined (__AVR_ATxmega128A1__)
    #define __BM_BOARD__ "ATxmega128A1"
  #elif defined (__AVR_ATxmega128A1U__)
    #define __BM_BOARD__ "ATxmega128A1U"
  #elif defined (__AVR_ATxmega128A4U__)
    #define __BM_BOARD__ "ATxmega128A4U"
  #elif defined (__AVR_ATxmega128A3__)
    #define __BM_BOARD__ "ATxmega128A3"
  #elif defined (__AVR_ATxmega128A3U__)
    #define __BM_BOARD__ "ATxmega128A3U"
  #elif defined (__AVR_ATxmega128B1__)
    #define __BM_BOARD__ "ATxmega128B1"
  #elif defined (__AVR_ATxmega128B3__)
    #define __BM_BOARD__ "ATxmega128B3"
  #elif defined (__AVR_ATxmega128C3__)
    #define __BM_BOARD__ "ATxmega128C3"
  #elif defined (__AVR_ATxmega128D3__)
    #define __BM_BOARD__ "ATxmega128D3"
  #elif defined (__AVR_ATxmega128D4__)
    #define __BM_BOARD__ "ATxmega128D4"
  #elif defined (__AVR_ATxmega192A3__)
    #define __BM_BOARD__ "ATxmega192A3"
  #elif defined (__AVR_ATxmega192A3U__)
    #define __BM_BOARD__ "ATxmega192A3U"
  #elif defined (__AVR_ATxmega192C3__)
    #define __BM_BOARD__ "ATxmega192C3"
  #elif defined (__AVR_ATxmega192D3__)
    #define __BM_BOARD__ "ATxmega192D3"
  #elif defined (__AVR_ATxmega256A3__)
    #define __BM_BOARD__ "ATxmega256A3"
  #elif defined (__AVR_ATxmega256A3U__)
    #define __BM_BOARD__ "ATxmega256A3U"
  #elif defined (__AVR_ATxmega256A3B__)
    #define __BM_BOARD__ "ATxmega256A3B"
  #elif defined (__AVR_ATxmega256A3BU__)
    #define __BM_BOARD__ "ATxmega256A3BU"
  #elif defined (__AVR_ATxmega256C3__)
    #define __BM_BOARD__ "ATxmega256C3"
  #elif defined (__AVR_ATxmega256D3__)
    #define __BM_BOARD__ "ATxmega256D3"
  #elif defined (__AVR_ATxmega384C3__)
    #define __BM_BOARD__ "ATxmega384C3"
  #elif defined (__AVR_ATxmega384D3__)
    #define __BM_BOARD__ "ATxmega384D3"
  #elif defined (__AVR_ATA5702M322__)
    #define __BM_BOARD__ "ATA5702M322"
  #elif defined (__AVR_ATA5782__)
    #define __BM_BOARD__ "ATA5782"
  #elif defined (__AVR_ATA5790__)
    #define __BM_BOARD__ "ATA5790"
  #elif defined (__AVR_ATA5790N__)
    #define __BM_BOARD__ "ATA5790N"
  #elif defined (__AVR_ATA5791__)
    #define __BM_BOARD__ "ATA5791"
  #elif defined (__AVR_ATA5831__)
    #define __BM_BOARD__ "ATA5831"
  #elif defined (__AVR_ATA5272__)
    #define __BM_BOARD__ "ATA5272"
  #elif defined (__AVR_ATA5505__)
    #define __BM_BOARD__ "ATA5505"
  #elif defined (__AVR_ATA5795__)
    #define __BM_BOARD__ "ATA5795"
  #elif defined (__AVR_ATA6285__)
    #define __BM_BOARD__ "ATA6285"
  #elif defined (__AVR_ATA6286__)
    #define __BM_BOARD__ "ATA6286"
  #elif defined (__AVR_ATA6289__)
    #define __BM_BOARD__ "ATA6289"
  #elif defined (__AVR_ATA6612C__)
    #define __BM_BOARD__ "ATA6612C"
  #elif defined (__AVR_ATA6613C__)
    #define __BM_BOARD__ "ATA6613C"
  #elif defined (__AVR_ATA6614Q__)
    #define __BM_BOARD__ "ATA6614Q"
  #elif defined (__AVR_ATA6616C__)
    #define __BM_BOARD__ "ATA6616C"
  #elif defined (__AVR_ATA6617C__)
    #define __BM_BOARD__ "ATA6617C"
  #elif defined (__AVR_ATA664251__)
    #define __BM_BOARD__ "ATA664251"
  #elif defined (__AVR_ATA8210__)
    #define __BM_BOARD__ "ATA8210"
  #elif defined (__AVR_ATA8510__)
    #define __BM_BOARD__ "ATA8510"
  #elif defined (__AVR_ATtiny28__)
    #define __BM_BOARD__ "ATtiny28"
  #elif defined (__AVR_AT90S1200__)
    #define __BM_BOARD__ "AT90S1200"
  #elif defined (__AVR_ATtiny15__)
    #define __BM_BOARD__ "ATtiny15"
  #elif defined (__AVR_ATtiny12__)
    #define __BM_BOARD__ "ATtiny12"
  #elif defined (__AVR_ATtiny11__)
    #define __BM_BOARD__ "ATtiny11"
  #elif defined (__AVR_M3000__)
    #define __BM_BOARD__ "M3000"
  #else
    #define __BM_BOARD__ "*UNKNOWN BOARD*"
  #endif
#endif

